name: Ghana maize seasonal forecast to DSSAT
country_code: GHA
country_name: Ghana
use_case_name: National
crop: Maize
zones:
  - Northern
  - Upper East
  - Upper West
  - Bono East
  - Ashanti
season_start_month: 5
season_start_day: 1
season_year: 2025
season_length_months: 5
lead_months: 1
n_cores: 4
variables:
  - PRCP
  - TMAX
  - TMIN
  - SRAD
manual_extent: true
extent:
  - 11.3
  - -3.5
  - 4.5
  - 1.4
skip_dssat: false
create_dssat_weather_files: false
varietyids:
  - 999993
