#!/usr/bin/env Rscript
###############################################################################
# Script: test_datasourcing_connection.R
# Purpose: Smoke test that this clone is correctly wired to the data_sourcing
# repo dependency (see README.md's "External repo dependencies" section) and
# is ready to run a full usecase through the agwise-datasourcing path.
#
# Deliberately makes no network calls and writes nothing to the shared
# filesystem: it exercises the real production entry point,
# generate_prestaged_dssat_via_datasourcing(), against usecases/configs/
# NGA/maize_test.yml, but only because that usecase's zone was already
# generated by a prior run - the function is idempotent and skips generation
# whenever EXTE#### sites already exist there. This script checks that
# up front and refuses to call the function if it isn't true anymore, so it
# never silently triggers a real SEAS5 download.
#
# Run: Rscript tests/test_datasourcing_connection.R
###############################################################################

fail <- function(...) { cat("FAIL:", ..., "\n"); quit(status = 1, save = "no") }
ok   <- function(...) cat("OK:", ..., "\n")

file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
script_dir <- if (length(file_arg)) {
  dirname(normalizePath(sub("^--file=", "", file_arg[[1]]), mustWork = TRUE))
} else {
  normalizePath("tests", mustWork = TRUE)
}
repo_root <- normalizePath(file.path(script_dir, ".."), mustWork = TRUE)
cat("repo_root:", repo_root, "\n\n")

# --- 1. Usecase config loads and actually exercises the datasourcing path ---
source(file.path(repo_root, "usecases", "00_usecase_helpers.R"))
config_path <- file.path(repo_root, "usecases", "configs", "NGA", "maize_test.yml")
if (!file.exists(config_path)) fail("Missing test config:", config_path)
usecase <- read_usecase_yaml(config_path)
ok("Loaded usecase config:", usecase$name)

source(file.path(repo_root, "main/DSSAT/00_load_packages.R"))
source(file.path(repo_root, "main/DSSAT/common_helpers.R"))
source(file.path(repo_root, "main/DSSAT/helpers_DSSAT_expfile.R"))
source(file.path(repo_root, "main/DSSAT/import_prestaged_dssat_files.R"))
source(file.path(repo_root, "main/DSSAT/run_datasourcing_export.R"))
source(file.path(repo_root, "main/DSSAT/run_dssat_pipeline.R"))
ok("Sourced the DSSAT pipeline scripts (same set run_dssat_pipeline() loads)")

complete_usecase <- load_dssat_defaults(usecase, repo_root)
if (!isTRUE(complete_usecase$skip_weather_soil_creation) ||
    !isTRUE(complete_usecase$generate_dssat_via_datasourcing)) {
  fail(
    "usecases/configs/NGA/maize_test.yml no longer sets skip_weather_soil_creation ",
    "+ generate_dssat_via_datasourcing - this test needs a config on the datasourcing path."
  )
}
ok("Usecase is on the datasourcing path (skip_weather_soil_creation + generate_dssat_via_datasourcing)")

# --- 2. datasourcing_repo_dir resolves to a real, sourceable R wrapper ---
datasourcing_repo_dir <- Sys.getenv("AGWISE_DATASOURCING_REPO_DIR", "~/agwise-datasourcing/code/data_sourcing")
agwise_data_r <- file.path(path.expand(datasourcing_repo_dir), "r", "agwise_data.R")
if (!file.exists(agwise_data_r)) fail("agwise_data.R not found at", agwise_data_r)
ok("data_sourcing repo found at", datasourcing_repo_dir)

if (!nzchar(Sys.getenv("AGWISE_DATA_BIN"))) {
  Sys.setenv(AGWISE_DATA_BIN = path.expand("~/agwise-datasourcing/envs/agwise_data/bin/agwise-data"))
}
source(agwise_data_r)
required_fns <- c("ad_bin", "ad_make_grid", "ad_forecast_to_dssat")
missing_fns <- required_fns[!vapply(required_fns, exists, logical(1), mode = "function")]
if (length(missing_fns)) fail("agwise_data.R sourced but missing expected function(s):", paste(missing_fns, collapse = ", "))
ok("agwise_data.R sourced;", paste(required_fns, collapse = ", "), "all defined")

# --- 3. agwise-data CLI binary is reachable and runs ---
bin <- ad_bin()
if (!file.exists(bin) && !nzchar(Sys.which(bin))) fail("agwise-data binary not found:", bin)
help_out <- suppressWarnings(system2(bin, "--help", stdout = TRUE, stderr = TRUE))
help_status <- attr(help_out, "status")
if (!is.null(help_status) && help_status != 0) fail("agwise-data --help exited non-zero (status", help_status, ")")
ok("agwise-data CLI responds:", bin)

# --- 4. Shared products directory is reachable ---
datasourcing_products_dir <- path.expand(Sys.getenv(
  "AGWISE_DATASOURCING_PRODUCTS_DIR",
  "~/agwise-datasourcing/dataops/datasourcing/Data/Global_GeoData/Processed/products"))
if (!dir.exists(datasourcing_products_dir)) fail("Products dir not found:", datasourcing_products_dir)
ok("Shared products dir reachable:", datasourcing_products_dir)

# --- 5. Exercise the real production entry point end-to-end ---
zone <- complete_usecase$zones[[1]]
out_dir <- file.path(datasourcing_products_dir, paste0(
  complete_usecase$country_code, "_", zone, "_forecast",
  complete_usecase$season_year, "_", complete_usecase$use_case_name))
existing_exte <- if (dir.exists(out_dir)) list.files(out_dir, pattern = "^EXTE") else character(0)

if (length(existing_exte) == 0) {
  cat(
    "SKIP: ", out_dir, " has no pre-staged EXTE sites - not calling ",
    "generate_prestaged_dssat_via_datasourcing() here, since that would trigger ",
    "a real SEAS5 download. Run it manually (or via `Rscript usecases/run_usecase.R ",
    "usecases/configs/NGA/maize_test.yml`) if you want to test the live path.\n", sep = ""
  )
} else {
  ok(length(existing_exte), "pre-staged EXTE sites already present in", out_dir)
  generate_prestaged_dssat_via_datasourcing(
    complete_usecase = complete_usecase, repo_root = repo_root,
    res_km = complete_usecase$resolution_km)
  ok("generate_prestaged_dssat_via_datasourcing() ran end-to-end (idempotent skip path, no network calls)")
}

cat(
  "\nAll checks passed. This clone is correctly wired to the shared data_sourcing repo\n",
  "and usecases/configs/NGA/maize_test.yml is ready to run in full via:\n",
  "  Rscript usecases/run_usecase.R usecases/configs/NGA/maize_test.yml\n",
  sep = ""
)
