
#!/usr/bin/env Rscript
###############################################################
# AgWise Bias Correction & Statistical Downscaling Module
# =======================================================
#
# Author: Jemal S. Ahmed
# Email: jemal.ahmed@cgiar.org
# Institution: Alliance of Bioversity International and CIAT (CGIAR)
# Date: 2026-05-29
#
# Concept
# -------
# This script performs bias correction and statistical downscaling
# of subseasonal–seasonal (S2S) or seasonal forecast data within the
# AgWise / AgWISE_Forecast workflow. It uses:
#
#   - Historical hindcast data to learn systematic model biases
#     relative to high-quality reference observations, and
#   - Applies the derived correction to real-time or target-year
#     forecasts to produce bias-adjusted, analysis-ready fields.
#
# The workflow is designed around:
#
#   * Scientific transparency:
#       - Explicit use of hindcasts for calibration only.
#       - Clearly defined reference period and spatial domain.
#   * Consistency across variables and models:
#       - Common folder structure shared with the Python
#         AgWise_Download module.
#       - Unified handling of multiple variables
#         (e.g. PRCP, TMAX, TMIN, TEMP, SRAD).
#   * Operational readiness:
#       - Inputs are taken from standardized "raw" directories
#         (obs + model files generated by Python).
#       - Outputs are written to "processed" directories, separated
#         by country, variable, and forecast year.
#
# Core logic
# ----------
# 1. Read country-specific configuration from 00_config_<COUNTRY>.R,
#    including:
#       - Base directories and country code
#       - Raw and processed folder paths
#       - Calibration years (hindcast period)
#       - Spatial domain (lon/lat limits)
#
# 2. For each variable of interest (e.g. PRCP, TMAX, TMIN, TEMP, SRAD):
#       - Load observation time series for the calibration period.
#       - Load hindcast model data for the same period.
#       - Load corresponding real-time forecasts to be corrected.
#
# 3. Perform bias correction / statistical downscaling:
#       - Estimate biases using hindcasts vs observations.
#       - Apply quantile delta mapping (QDM) or similar method
#         to the forecast data, treating hindcasts only as the
#         calibration set.
#
# 4. Export bias-corrected forecasts:
#       - Save corrected forecast fields as NetCDF in a consistent
#         naming convention under:
#           processed/bias_corrected/forecast/
#       - Optionally generate spatial bias maps for diagnostic
#         purposes (hindcast vs obs, and bias-corrected forecast).
#
# Intended use
# ------------
# This module serves as the R-based post-processing layer for
# AgWise / AgWISE_Forecast and related national agro-climate
# advisory systems. It bridges raw model output and downstream
# applications such as:
#
#   - Agro-climate indices and extremes,
#   - Crop and livestock models (e.g. DSSAT),
#   - Advisory products and decision-support tools,
#   - Skill assessment and verification workflows.
#
# Author
# ------
# Jemal Seid Ahmed, Wuletaw Abera
# Alliance of Bioversity International & CIAT (CGIAR)
# Email: jemal.ahmed@cgiar.org
#
# Date: July 2025
# Version: 1.5
###############################################################
options(warn = -1)
source("00_config_function.R") 

###############################################################


# Path

run_agwise_seasonal_forecast_BC <- function(
    country_code = "KEN",
    init_month_user = 10, 
    init_day_user = 1,
    season_length_months = 3,
    forecast_year = as.integer(format(Sys.Date(), "%Y")),
    forecast_lead_months = 1,
    use_manual_extent = FALSE, extent_manual = c(16, 34, 8, 40),
    manual_domain_name = "User_Domain",
    base_dir=normalizePath("../../data", mustWork = FALSE),
    main_script_dir = normalizePath(".", mustWork = TRUE),
    py_path = "/opt/anaconda3/envs/WASS2S/bin/python",
    py_script = file.path(main_script_dir, "02_run_agwise_multi_country.py"),
    dssat_geo_script = file.path(main_script_dir, "04_prepare_dssat_geo_inputs.R"),
    variables_to_bc = c("PRCP", "TMAX", "TMIN", "TEMP", "SRAD"),
    force_download = FALSE,
    export_dssat = TRUE,
    n_cores = NULL,
    run_downloader = TRUE,
    parallel_backend = c("auto", "process", "fork", "none")
) {
  
    setwd(main_script_dir)
    parallel_backend <- match.arg(parallel_backend)
      
    #############################################################
    # 1 Build country configration files for both forecast and bias correction
    ###############################################################
    
    build_country_config(country_code = country_code, base_dir = base_dir, 
                         use_manual_extent = use_manual_extent, extent_manual = extent_manual,
                         manual_domain_name = manual_domain_name,
                         init_month_user = init_month_user, init_day_user = init_day_user,
                         season_length_months = season_length_months,
                         forecast_year = forecast_year,
                         forecast_lead_months = forecast_lead_months)
    
    
    config_json_path <- file.path(
      country_data_dir(base_dir, country_code), "config",
      paste0(country_code, "_config_agwise.json"))
    aoi_config <- load_country_config_from_json(config_json_path)
    season_length <- aoi_config$season_length_months
    if (is.null(season_length) || is.na(season_length)) season_length <- 3
    seasons <- ((aoi_config$init_month - 1 + 0:(season_length - 1)) %% 12) + 1
    forecast_dates_from_file <- function(path) {
      nc <- ncdf4::nc_open(path)
      on.exit(ncdf4::nc_close(nc), add = TRUE)
      time_dim <- nc$dim[["time"]]
      if (is.null(time_dim)) time_dim <- nc$dim[["T"]]
      if (is.null(time_dim)) {
        stop("Forecast file has no time dimension: ", path)
      }
      units <- time_dim$units
      vals <- time_dim$vals
      if (is.null(units) || length(vals) < 1) {
        stop("Forecast file has no valid time coordinate: ", path)
      }
      origin_text <- sub("^[A-Za-z]+ since[[:space:]]+", "", units)
      origin_text <- sub("[[:space:]]+UTC$", "", origin_text)
      origin <- as.POSIXct(origin_text, tz = "UTC")
      if (is.na(origin)) {
        origin <- as.POSIXct(as.Date(origin_text), tz = "UTC")
      }
      unit_name <- tolower(strsplit(units, "[[:space:]]+")[[1]][1])
      multiplier <- switch(unit_name,
        "days" = 86400, "day" = 86400,
        "hours" = 3600, "hour" = 3600,
        "minutes" = 60, "minute" = 60,
        "seconds" = 1, "second" = 1,
        stop("Unsupported time units in forecast file: ", units)
      )
      as.Date(origin + vals * multiplier, tz = "UTC")
    }
    forecast_months_from_file <- function(path) {
      dates <- forecast_dates_from_file(path)
      dates <- dates[!is.na(dates)]
      if (length(dates) < 1) {
        stop("Forecast file has no valid daily time coordinate: ", path)
      }
      unique(as.integer(format(dates, "%m")))
    }
    format_months <- function(months) {
      paste(sprintf("%02d", months), collapse = ",")
    }
    resolve_n_cores <- function(requested = NULL) {
      requested <- suppressWarnings(as.integer(requested))
      detected <- suppressWarnings(parallel::detectCores())
      if (!is.finite(detected) || is.na(detected)) detected <- NA_integer_

      if (!length(requested) || !is.finite(requested) || is.na(requested) || requested < 1L) {
        requested <- if (is.na(detected)) 1L else max(1L, detected - 1L)
      }
      if (!is.na(detected)) requested <- min(requested, detected)
      max(1L, requested)
    }
    can_use_downscaler_parallel <- function(cores) {
      if (!isTRUE(cores > 1L)) return(FALSE)
      cl <- try(parallel::makeCluster(cores, type = "FORK"), silent = TRUE)
      if (inherits(cl, "try-error")) return(FALSE)
      parallel::stopCluster(cl)
      TRUE
    }
    r_quote <- function(x) {
      paste0('"', gsub('(["\\\\])', '\\\\\\1', x), '"')
    }
    r_bool <- function(x) {
      if (isTRUE(x)) "TRUE" else "FALSE"
    }
    r_num_vec <- function(x) {
      paste0("c(", paste(as.numeric(x), collapse = ","), ")")
    }
    r_char_vec <- function(x) {
      paste0("c(", paste(vapply(x, r_quote, character(1)), collapse = ","), ")")
    }
    configured_init_token <- function(year = NULL) {
      token <- paste0(month.abb[as.integer(aoi_config$init_month)], as.integer(aoi_config$init_day))
      if (!is.null(year)) token <- paste0(token, "_", as.integer(year))
      paste0("_", token, "_")
    }
    n_cores <- resolve_n_cores(n_cores)
    message("Bias-correction core budget: ", n_cores)

    
    t_all <- Sys.time()
    
    t_down <- Sys.time()
    #############################################################
    # 2 Run Python multi-country downloader & lead time forecast BEFORE bias correction
    ###############################################################
    if (isTRUE(run_downloader)) {
      message("Running AgWise Python downloader for country: ", country_code)

      py_cmd    <- sprintf("%s %s --data-dir %s --countries %s", shQuote(py_path), shQuote(py_script),shQuote(base_dir), shQuote(country_code))
      if (isTRUE(force_download)) py_cmd <- paste(py_cmd, "--force-download")

      # Execute command
      status <- system(py_cmd, intern = TRUE)
      py_status <- attr(status, "status")

      message("Python downloader output:")
      print(status)
      if (!is.null(py_status) && py_status != 0) {
        stop("Python downloader failed with exit status ", py_status)
      }
    } else {
      message("Skipping Python downloader in bias-correction worker.")
    }
    message("Downloader finished Time: ", round(difftime(Sys.time(), t_down, units = "mins"), 2), " min")
    
    message("Proceeding to bias correction.........")

    run_dssat_export <- function() {
      if (!isTRUE(export_dssat)) return(invisible(NULL))
      message("Preparing DSSAT geo RDS forecast inputs for readGeo_CM_zone.R...")
      t_dssat <- Sys.time()
      tmp_dir <- Sys.getenv(
        "TMPDIR",
        unset = "/Volumes/T7/tmp"
      )
      dir.create(tmp_dir, recursive = TRUE, showWarnings = FALSE)
      dssat_status <- system2(
        "Rscript",
        args = c(dssat_geo_script, "--config", config_json_path, "--overwrite"),
        stdout = TRUE,
        stderr = TRUE,
        env = paste0("TMPDIR=", tmp_dir)
      )
      dssat_exit <- attr(dssat_status, "status")
      message("DSSAT geo input preparation output:")
      print(dssat_status)
      if (!is.null(dssat_exit) && dssat_exit != 0) {
        stop("DSSAT geo input preparation failed with exit status ", dssat_exit)
      }
      message("DSSAT geo input preparation time: ", round(difftime(Sys.time(), t_dssat, units = "mins"), 2), " min")
      invisible(dssat_status)
    }
    
    #############################################################
    ###3 Bias Correction based on Observation, hindicast and forecast data
    #############################################################
    
    bc_var_cfg <- list(
      PRCP = list(obs_file_pattern="Daily_PRCP_%d_%d.nc", obs_var="precip",
                  model_var="PRCP", is_precip=TRUE, method="ptr",
                  scaling.type="multiplicative", units="mm/day"),
      TMAX = list(obs_file_pattern="Daily_TMAX_%d_%d.nc", obs_var="TMAX",
                  model_var="TMAX", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      TMIN = list(obs_file_pattern="Daily_TMIN_%d_%d.nc", obs_var="TMIN",
                  model_var="TMIN", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      TEMP = list(obs_file_pattern="Daily_TEMP_%d_%d.nc", obs_var="TEMP",
                  model_var="TEMP", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      SRAD = list(obs_file_pattern="Daily_SRAD_%d_%d.nc", obs_var="SRAD",
                  model_var="SRAD", is_precip=FALSE, method="qdm",
                  scaling.type="multiplicative", units="MJ/m2/day"))
    
    ## Variables to process
    variables_to_bc <- intersect(variables_to_bc, names(bc_var_cfg))
    
    if (length(variables_to_bc) == 0) {
      stop("No valid variables selected for bias correction.")
    }

    if (parallel_backend == "auto") {
      parallel_backend <- if (isTRUE(run_downloader) && n_cores > 1L && length(variables_to_bc) > 1L) "process" else "none"
    }

    run_variable_worker <- function(var_code) {
      log_dir <- file.path(country_data_dir(base_dir, country_code), "forecast", "logs")
      dir.create(log_dir, recursive = TRUE, showWarnings = FALSE)
      log_file <- file.path(
        log_dir,
        paste0("bias_correction_", var_code, "_", format(Sys.time(), "%Y%m%d%H%M%S"), "_pid", Sys.getpid(), ".log")
      )
      expr <- paste0(
        "source(", r_quote(file.path(main_script_dir, "03_bias_correction_forecast_multiVar.R")), "); ",
        "run_agwise_seasonal_forecast_BC(",
        "country_code=", r_quote(country_code),
        ", init_month_user=", as.integer(init_month_user),
        ", init_day_user=", as.integer(init_day_user),
        ", season_length_months=", as.integer(season_length_months),
        ", forecast_year=", as.integer(forecast_year),
        ", forecast_lead_months=", as.integer(forecast_lead_months),
        ", use_manual_extent=", r_bool(use_manual_extent),
        ", extent_manual=", r_num_vec(extent_manual),
        ", manual_domain_name=", r_quote(manual_domain_name),
        ", base_dir=", r_quote(normalizePath(base_dir, mustWork = FALSE)),
        ", main_script_dir=", r_quote(normalizePath(main_script_dir, mustWork = TRUE)),
        ", py_path=", r_quote(py_path),
        ", py_script=", r_quote(py_script),
        ", dssat_geo_script=", r_quote(dssat_geo_script),
        ", variables_to_bc=", r_char_vec(var_code),
        ", force_download=FALSE",
        ", export_dssat=FALSE",
        ", n_cores=1",
        ", run_downloader=FALSE",
        ", parallel_backend=\"none\"",
        ")"
      )
      env <- c(
        paste0("TMPDIR=", Sys.getenv("TMPDIR", unset = "/Volumes/T7/tmp")),
        "OMP_NUM_THREADS=1",
        "OPENBLAS_NUM_THREADS=1",
        "MKL_NUM_THREADS=1",
        "VECLIB_MAXIMUM_THREADS=1",
        "NUMEXPR_NUM_THREADS=1"
      )
      status <- system2("Rscript", c("-e", shQuote(expr)), stdout = log_file, stderr = log_file, env = env)
      list(status = status, var_code = var_code, log_file = log_file)
    }

    if (parallel_backend == "process" && isTRUE(run_downloader) && n_cores > 1L && length(variables_to_bc) > 1L) {
      worker_cores <- min(n_cores, length(variables_to_bc))
      message(
        "Launching process-level bias correction: ", length(variables_to_bc),
        " variable worker(s), ", worker_cores, " concurrent Rscript process(es)."
      )
      worker_results <- parallel::mclapply(
        variables_to_bc, run_variable_worker,
        mc.cores = worker_cores, mc.preschedule = FALSE
      )
      failed <- vapply(worker_results, function(x) !identical(as.integer(x$status), 0L), logical(1))
      if (any(failed)) {
        details <- vapply(worker_results[failed], function(x) {
          paste0(x$var_code, " failed with status ", x$status, ". Log: ", x$log_file)
        }, character(1))
        stop("Parallel bias-correction worker failure(s):\n", paste(details, collapse = "\n"))
      }
      message("Process-level bias correction completed. Worker logs:")
      print(vapply(worker_results, `[[`, character(1), "log_file"))
      run_dssat_export()
      message("Forecast is ready for all variables: Total runtime: ", round(difftime(Sys.time(), t_all, units = "mins"), 2), " min")
      return(invisible(worker_results))
    }
    
    process_bc_job <- function(job) {
      var_code <- job$var_code
      cfg <- job$cfg
      m <- job$model_id
      obs_file <- job$obs_file
      hind_file <- job$hind_file
      fcst_file <- job$fcst_file
      years_calib <- job$years_calib
      forecast_months <- job$forecast_months
      inner_cores <- job$inner_cores
      use_inner_parallel <- isTRUE(job$use_inner_parallel && inner_cores > 1L)

      if (job$outer_parallel) {
        Sys.setenv(
          OMP_NUM_THREADS = "1",
          OPENBLAS_NUM_THREADS = "1",
          MKL_NUM_THREADS = "1",
          VECLIB_MAXIMUM_THREADS = "1",
          NUMEXPR_NUM_THREADS = "1"
        )
      }

      message("---------------------------------------------------")
      message("Processing ", var_code, " for model ID: ", m)
      message("  Hindcast file: ", hind_file)
      message("  Forecast file: ", fcst_file)
      message("  Forecast lead months used for BC: ", format_months(forecast_months))
      message("  Worker PID: ", Sys.getpid(), " | downscaleR internal cores: ",
              ifelse(use_inner_parallel, inner_cores, 1L))

      ###########################################################
      # 4.3 Load observed calibration data (reference)
      ###########################################################
      nc_obs <- loadGridData(dataset = obs_file, season = forecast_months, var = cfg$obs_var,
        lonLim  = c(aoi_config$extent_obs[2], aoi_config$extent_obs[4]),
        latLim  = c(aoi_config$extent_obs[3], aoi_config$extent_obs[1]),
        years   = years_calib )
      attr(nc_obs$Variable, "units") <- cfg$units

      #--------------------------------------------------------
      # 4.4.1 Load hindcast (calibration) data
      #--------------------------------------------------------
      nc_hind <- tryCatch({
        loadGridData(
          dataset = hind_file,
          var     = cfg$model_var,
          season = forecast_months,
          lonLim  = c(aoi_config$extent_model[2], aoi_config$extent_model[4]),
          latLim  = c(aoi_config$extent_model[3], aoi_config$extent_model[1]),
          years   = years_calib
        )
      }, error = function(e) {
        message("  Failed to load hindcast: ", hind_file)
        message("  Error: ", e$message)
        return(NULL)
      })

      if (is.null(nc_hind)) {
        message("  -> Hindcast load returned NULL, skipping model ", m)
        return(list(status = "skipped", var_code = var_code, model_id = m,
                    reason = "hindcast load returned NULL"))
      }

      #--------------------------------------------------------
      # 4.4.2 Load forecast data (to be bias-corrected)
      #--------------------------------------------------------
      nc_fcst <- tryCatch({
        loadGridData(
          dataset = fcst_file,
          var     = cfg$model_var,
          season = forecast_months,
          lonLim  = c(aoi_config$extent_model[2], aoi_config$extent_model[4]),
          latLim  = c(aoi_config$extent_model[3], aoi_config$extent_model[1])
          ## Keep all available forecast years/lead times; do not pass
          ## years= here because operational forecasts may span years.
        )
      }, error = function(e) {
        message("  Failed to load forecast: ", fcst_file)
        message("  Error: ", e$message)
        return(NULL)
      })

      if (is.null(nc_fcst)) {
        message("  -> Forecast load returned NULL, skipping model ", m)
        return(list(status = "skipped", var_code = var_code, model_id = m,
                    reason = "forecast load returned NULL"))
      }

      #--------------------------------------------------------
      # 4.4.3 Bias correction: hindcast calibrates, forecast is newdata
      #--------------------------------------------------------
      t_bc <- Sys.time()

      message("  -> Running biasCorrection (using hindcast as training data, forecast as newdata)...")
      bc_method <- cfg$method
      if (is.null(bc_method) || is.na(bc_method)) {
        bc_method <- if (cfg$is_precip) "ptr" else "qdm"
      }
      if (!cfg$is_precip && tolower(bc_method) == "ptr") {
        warning("PTR is only valid for precipitation; using QDM for ", var_code, ".")
        bc_method <- "qdm"
      }
      nc_fcst_bc <- biasCorrection(y = nc_obs, x = nc_hind, newdata = nc_fcst,
        precipitation = cfg$is_precip, window = c(30, 7), method = bc_method,
        #cross.val     = "kfold",
        #folds = list(1990:1996, 1997:2002, 2011:2016),
        #consecutive   = cfg$is_precip,
        scaling.type  = cfg$scaling.type, parallel = use_inner_parallel,
        max.ncores = inner_cores, ncores = inner_cores )

      ## Bias-corrected forecast regridded to obs grid
      nc_fcst_bc_interp <- interpGrid(nc_fcst_bc, getGrid(nc_obs), ncores = inner_cores)

      message("BC time: ", round(difftime(Sys.time(), t_bc, units = "mins"), 2), " min")

      #--------------------------------------------------------
      # 4.4.4 Export bias-corrected FORECAST only
      #--------------------------------------------------------
      fcst_years_str <- paste(aoi_config$forecast_year, collapse = "-")
      outFile <- file.path(aoi_config$dir_bc_fcst,
        sprintf("%s_daily_%s_forecast_BC_%s.nc", var_code, m, fcst_years_str))

      message("  -> Writing bias-corrected FORECAST NetCDF: ", outFile)
      t_nc <- Sys.time()

      nc_fcst_bc_interp$Variable$varName = cfg$model_var
      attr(nc_fcst_bc_interp$Variable, "longname") <- "Bias-corrected seasonal forecast"

      nc_bc_rast <- terra::rast(grid2sp(nc_fcst_bc_interp))
      time(nc_bc_rast) <- as.Date(nc_fcst_bc_interp$Dates$start)

      aoi <- terra::vect(file.path(aoi_config$dir_raw_admin, "gadm",
                                   paste0("gadm41_", country_code, "_0_pk.rds")))
      nc_bc_rast_masked <- terra::mask(nc_bc_rast, aoi)

      terra::writeCDF(x = nc_bc_rast_masked, filename = outFile,
                      varname = as.character(nc_fcst_bc_interp$Variable$varName),
                      unit    = as.character(attr(nc_fcst_bc_interp$Variable, "units")),
                      atts     = globalAttributeList,
                      prec     = "double", missval  = -999, compression = 9, overwrite = TRUE)

      message("NetCDF write time: ", round(difftime(Sys.time(), t_nc, units = "secs"), 1), " s")
      message("  -> Finished ", var_code, " for model ID: ", m)

      list(status = "ok", var_code = var_code, model_id = m, outFile = outFile)
    }

    run_bc_job_safely <- function(job) {
      tryCatch(
        process_bc_job(job),
        error = function(e) {
          list(status = "error", var_code = job$var_code,
               model_id = job$model_id, reason = conditionMessage(e))
        }
      )
    }

    ###############################################################
    # 4. Build independent variable/model jobs, then run in parallel
    ###############################################################
    years_calib <- c(aoi_config$year_hndS:aoi_config$year_hndE)
    jobs <- list()
    for (var_code in variables_to_bc) {
      cfg <- bc_var_cfg[[var_code]]
      message("===================================================")
      message("Variable: ", var_code)
      message(" -> obs_file_pattern: ", cfg$obs_file_pattern)
      message(" -> obs_var: ", cfg$obs_var, " | model_var: ", cfg$model_var)

      obs_file <- file.path(aoi_config$dir_raw_obs, 
                          sprintf(cfg$obs_file_pattern, aoi_config$year_start_obs, aoi_config$year_end_obs))

      ###########################################################
      # 4.2 Hindcast & forecast files for this variable
      #     Python naming:
      #       hindcast_<modelid>_<VAR>_...
      #       forecast_<modelid>_<VAR>_...
      ###########################################################
      hind_pattern <- sprintf("^hindcast_.*_%s_.*\\.nc$", var_code)
      fcst_pattern <- sprintf("^forecast_.*_%s_.*\\.nc$", var_code)
      
      hind_files <- list.files(aoi_config$dir_raw_model, pattern = hind_pattern,  full.names = TRUE)
      fcst_files <- list.files(aoi_config$dir_raw_model, pattern = fcst_pattern,full.names = TRUE)
      hind_files <- hind_files[grepl(configured_init_token(), basename(hind_files), fixed = TRUE)]
      fcst_files <- fcst_files[grepl(
        configured_init_token(aoi_config$forecast_init_year),
        basename(fcst_files),
        fixed = TRUE
      )]
      if (length(hind_files) == 0) {
        message("  !! No hindcast files found for configured initialization token: ", configured_init_token())
      }
      if (length(fcst_files) == 0) {
        message(
          "  !! No forecast files found for configured initialization token: ",
          configured_init_token(aoi_config$forecast_init_year)
        )
      }
      
      ## Extract model IDs (e.g. "ecmwf51") so we can pair hindcast + forecast
      hind_ids <- sub("^hindcast_([^_]+)_.+\\.nc$", "\\1", basename(hind_files))
      fcst_ids <- sub("^forecast_([^_]+)_.+\\.nc$", "\\1", basename(fcst_files))
      
      model_ids <- intersect(unique(hind_ids), unique(fcst_ids))
      if (length(model_ids) == 0) {
        message("  !! No common model IDs between hindcast and forecast for ", var_code)
        next
      }

      for (m in model_ids) {
        hind_file <- hind_files[hind_ids == m][1]
        fcst_file <- fcst_files[fcst_ids == m][1]
        forecast_months <- forecast_months_from_file(fcst_file)
        jobs[[length(jobs) + 1L]] <- list(
          var_code = var_code, cfg = cfg, model_id = m,
          obs_file = obs_file, hind_file = hind_file, fcst_file = fcst_file,
          years_calib = years_calib, forecast_months = forecast_months
        )
      }
    }

    if (length(jobs) < 1L) {
      stop("No bias-correction jobs were created. Check raw model files and selected variables.")
    }
    outer_cores <- if (parallel_backend == "fork" && .Platform$OS.type != "windows") min(n_cores, length(jobs)) else 1L
    inner_cores <- if (outer_cores > 1L) 1L else n_cores
    use_inner_parallel <- outer_cores == 1L && can_use_downscaler_parallel(inner_cores)
    if (outer_cores == 1L && inner_cores > 1L && !use_inner_parallel) {
      message("downscaleR internal parallel backend is unavailable; running this job sequentially.")
    }
    jobs <- lapply(jobs, function(job) {
      job$outer_parallel <- outer_cores > 1L
      job$inner_cores <- inner_cores
      job$use_inner_parallel <- use_inner_parallel
      job
    })

    message(
      "Bias-correction jobs: ", length(jobs),
      " | outer workers: ", outer_cores,
      " | downscaleR internal cores per job: ", ifelse(use_inner_parallel, inner_cores, 1L)
    )

    bc_results <- if (outer_cores > 1L) {
      parallel::mclapply(jobs, run_bc_job_safely, mc.cores = outer_cores, mc.preschedule = FALSE)
    } else {
      lapply(jobs, run_bc_job_safely)
    }

    failed <- vapply(bc_results, function(x) identical(x$status, "error"), logical(1))
    if (any(failed)) {
      details <- vapply(bc_results[failed], function(x) {
        paste0(x$var_code, "/", x$model_id, ": ", x$reason)
      }, character(1))
      stop("Bias correction failed for job(s):\n", paste(details, collapse = "\n"))
    }
    skipped <- vapply(bc_results, function(x) identical(x$status, "skipped"), logical(1))
    if (any(skipped)) {
      details <- vapply(bc_results[skipped], function(x) {
        paste0(x$var_code, "/", x$model_id, ": ", x$reason)
      }, character(1))
      message("Skipped bias-correction job(s):\n", paste(details, collapse = "\n"))
    }
    message("Completed bias-correction jobs: ", sum(vapply(bc_results, function(x) identical(x$status, "ok"), logical(1))))
    
    run_dssat_export()
    
    message("Forecast is ready for all variables: Total runtime: ", round(difftime(Sys.time(), t_all, units = "mins"), 2), " min")
}
